/**
 * The NZBeam plugin SDK, version 1.1.
 *
 * Generated from `sdk/index.ts` by `bun run sdk:build` — do not edit this file by hand; edit
 * that one and run the script. It is the same surface with every type the app shares inlined,
 * so that it stands on its own: point a plugin at it and nothing else is needed.
 *
 *   { "compilerOptions": { "paths": { "nzbeam/sdk": ["./nzbeam-sdk.ts"] } } }
 *
 * At runtime `nzbeam/sdk` is a module the app provides, and `definePlugin` is all of it. The
 * version above is this file's, not something to read at runtime: stamp the pair your plugin
 * was written against into its manifest as literals.
 *
 * A plugin built for another version is not turned away. It loads, switches on and runs, and
 * the difference shows on its row in the app. What one major takes away keeps working through
 * the next before it goes, so one major behind is inside that window and further back is not.
 */

import type { Database } from 'bun:sqlite'

// --- The app's own types, inlined so this file stands alone

// From shared/types/category.ts

export interface Category {
  id: number
  name: string
  path: string
  /** ISO 8601 UTC timestamps. */
  createdAt: string
  updatedAt: string
}

// From shared/types/download.ts

export interface Download {
  id: number
  /** The job name: the NZB file's name without its extension. Also the folder the result lands in. */
  name: string
  status: DownloadStatus
  /** The category whose folder the result goes to, or null for the default downloads folder. */
  categoryId: number | null
  /** That category's name, or null when there is none (or it has since been deleted). */
  categoryName: string | null
  /** What the NZB says the articles add up to, so roughly what has to come down the wire. */
  totalBytes: number
  downloadedBytes: number
  totalArticles: number
  doneArticles: number
  /** Articles no server had. par2 may still make up for them. */
  missingArticles: number
  /** How fast articles are coming in right now; 0 whenever nothing is being fetched. */
  bytesPerSecond: number
  /** How far the current post-processing step has got, 0 to 100, or null when the step has not said. */
  stagePercent: number | null
  /** What that step is doing in its own words (par2's `scanning`, `repairing`), or null. */
  stageDetail: string | null
  /** When false the download is fetched and moved as it is, with no par2 or unrar step. */
  postProcess: boolean
  /** Why it failed, or null. */
  error: string | null
  /**
   * The step it failed in, or null while it has not failed. A download that failed in its moving
   * step is all there: its files wait in the temp folder for a place they can be moved to.
   */
  failedStage: DownloadStep | null
  /**
   * Where the finished download was put, once it has been: its own folder under the category's,
   * or the category's own folder when a plugin placed every one of its files and there was
   * nothing left to make a folder for.
   */
  finalPath: string | null
  /** ISO 8601 UTC timestamps. */
  createdAt: string
  startedAt: string | null
  finishedAt: string | null
  updatedAt: string
}

/** The post-processing steps, each of which is also a status the download shows while in it. */
export type PostProcessStage = Extract<DownloadStatus, 'verifying' | 'extracting' | 'moving'>

/**
 * Where a download is in its life. Queued waits its turn; paused waits until somebody says
 * otherwise, keeping whatever it had fetched; downloading fetches the articles into the temp
 * folder; verifying runs par2 over what arrived; extracting unpacks the archives; moving puts the
 * result in its category's folder. Completed and failed are where it ends up.
 */
export type DownloadStatus =
  | 'queued'
  | 'paused'
  | 'downloading'
  | 'verifying'
  | 'extracting'
  | 'moving'
  | 'completed'
  | 'failed'

/** The steps that do work, so the ones a download can fail in. */
export type DownloadStep = Extract<DownloadStatus, 'downloading'> | PostProcessStage

// From shared/types/notification.ts

/**
 * An event as a plugin's notification target is handed it: a title and a plain-text rendering
 * every chat target can post as it is, the lines the text was made of, and the payload the
 * custom webhook would get, for a target that wants the numbers.
 */
export interface NotificationMessage {
  event: NotificationEvent
  at: string
  title: string
  text: string
  lines: { label: string, value: string }[]
  /** For a download's event: how the download went, as the custom webhook is told it. */
  download: DownloadEventPayload['download'] | null
  /** For a plugin's message: which plugin, and what it said. */
  plugin: { id: string, name: string } | null
  message: string | null
}

/**
 * What the app sends word of. A download finishing covers both ways it can end: the message says
 * whether it completed or failed, and looks different for each. Paused is a download set aside,
 * on its own or with the queue; resumed is the queue picking it up again from where it was. A
 * plugin message is whatever a plugin has to say, through the targets that asked to hear from plugins.
 */
export type NotificationEvent = 'download.started' | 'download.paused' | 'download.resumed' | 'download.finished' | 'plugin.message'

/**
 * What a custom webhook is sent for a download's event: the download as it stands, with the two
 * timestamps and what they add up to, where it is headed and where it ended up. The same shape for
 * both events, so whatever reads it can treat the two alike; `status` is what tells a finish that
 * went well from one that did not.
 */
export interface DownloadEventPayload {
  event: DownloadEvent['event']
  /** When this was sent. */
  at: string
  download: {
    id: number
    name: string
    status: DownloadStatus
    category: string | null
    /** What the NZB says the release adds up to. */
    sizeBytes: number
    downloadedBytes: number
    /** How far along the download is, 0 to 100: what a paused one had got, say. */
    percent: number
    missingArticles: number
    startedAt: string | null
    finishedAt: string | null
    durationSeconds: number | null
    /** The folder the download is (or was) headed for. */
    destination: string
    /** Where it ended up, once it has. */
    finalPath: string | null
    /** Why it failed, when it did. */
    error: string | null
  }
}

/** What happened to a download, as the queue tells the notifications about it. */
export interface DownloadEvent {
  event: DownloadEventName
  /** The download as it stands: for `download.finished`, either completed or failed. */
  download: Download
  /** The folder the download is (or was) headed for. */
  destination: string
}

/** The events a download goes through, as the notifications and the plugins are told of them. */
export type DownloadEventName = Exclude<NotificationEvent, 'plugin.message'>

// From shared/types/plugin.ts

/**
 * Who may call one of a plugin's routes.
 *
 * `session` is the app's own sign-in, as every other page and API route: the default, and the
 * only one a browser tab needs. `token` opens the route to the outside, to whoever sends the
 * plugin's token with the call — a webhook from Sonarr or uptime-kuma, a Shortcut on a phone.
 * `public` opens it to anyone at all, for a caller that cannot be given a token of ours and
 * proves itself to the handler instead: Telegram signs its updates with a secret of its own,
 * GitHub with a signature over the body.
 */
export type PluginRouteAccess = 'session' | 'token' | 'public'

// --- Routes a plugin declares

export type PluginRouteMethod = 'GET' | 'POST' | 'PUT' | 'DELETE'

/** The fields in the order the form shows them. */
export type PluginSchema = Record<string, PluginField>

/** The settings a schema yields, each field as its own type. */
export type PluginSettingsOf<S extends PluginSchema> = { [K in keyof S]: PluginFieldValue<S[K]> }

export type PluginField =
  | PluginStringField
  | PluginNumberField
  | PluginBooleanField
  | PluginSelectField
  | PluginListField

/** Settings as they are stored and sent: the same shape, without knowing the schema. */
export type PluginSettings = Record<string, string | number | boolean | string[]>

/** What one field holds once validated. */
export type PluginFieldValue<F extends PluginField> =
  F extends PluginStringField ? string
    : F extends PluginNumberField ? number
      : F extends PluginBooleanField ? boolean
        : F extends PluginListField ? string[]
          : F extends PluginSelectField ? string
            : never

export interface PluginStringField extends PluginFieldBase {
  /**
   * `text` is a multi-line box; `password` is masked; `path` is a folder on disk, offered the
   * folders inside whatever has been typed so far.
   */
  type: 'string' | 'password' | 'text' | 'path'
  default?: string
  maxLength?: number
}

export interface PluginNumberField extends PluginFieldBase {
  type: 'number'
  default?: number
  min?: number
  max?: number
  /** When true anything with a fraction is turned away. */
  integer?: boolean
}

export interface PluginBooleanField extends PluginFieldBase {
  type: 'boolean'
  default?: boolean
  /** How the switch reads while on, and while off. */
  on?: string
  off?: string
}

/**
 * A choice out of a list. The list is either written into the manifest as `options`, or named by
 * `optionsFrom` and fetched from the plugin when the form is drawn — for choices only the plugin
 * knows, such as the libraries a Plex server holds. Exactly one of the two.
 */
export interface PluginSelectField extends PluginFieldBase {
  type: 'select'
  /** The choices, when they are known ahead of time. */
  options?: { value: string, label: string }[]
  /**
   * The name of one of the plugin's `options` providers, for choices that are looked up. The form
   * asks `GET /api/plugins/<id>/options/<name>` for them; what is saved is whatever was picked,
   * since the list may have moved on by the time the plugin reads it.
   */
  optionsFrom?: string
  default?: string
}

/** A list of lines, added and removed a row at a time. Blank rows are dropped on save. */
export interface PluginListField extends PluginFieldBase {
  type: 'list'
  default?: string[]
  /** At most this many rows; the app's own ceiling when left out. */
  maxItems?: number
  /** Per row. */
  maxLength?: number
}

/**
 * Plugins: code the admin drops into the `/plugins` mount, loaded at startup and on "Reload
 * plugins", that hooks into what the app does. Everything the page and the API need to show and
 * manage one is here; what a plugin itself is written against — the contexts its hooks get — is
 * the SDK in `sdk/index.ts`, which builds on these.
 */

// --- The settings schema a plugin declares, and the values it yields

interface PluginFieldBase {
  label: string
  hint?: string
  placeholder?: string
  /** When true an empty value is turned away on save. Off, the field may be left blank. */
  required?: boolean
}

// From shared/types/rss-feed.ts

export interface RssFeed {
  id: number
  name: string
  /** Full feed URL, including any token or API key in its query string. */
  url: string
  /** How often the feed is read. */
  intervalMinutes: number
  /** Category whose folder the feed's downloads go to, or null for no category. */
  categoryId: number | null
  /** When false the feed is only ever read by hand, never on its interval. */
  enabled: boolean
  /** When the feed was last read successfully, or null while it never has been. */
  lastReadAt: string | null
  createdAt: string
  updatedAt: string
}

// From shared/types/server.ts

/** A Usenet (NNTP) server that articles are downloaded from. */
export interface Server {
  id: number
  name: string
  host: string
  port: number
  /** Whether the connection is made over TLS. */
  ssl: boolean
  certificateVerification: CertificateVerification
  /** Empty when the server asks for no login. */
  username: string
  /** Kept as entered, like a feed URL's token: the downloader has to send it, so it cannot be hashed. */
  password: string
  /** How many connections the downloader may hold open at once. */
  connections: number
  /** 0 is tried first; a higher number is only used once every lower one has failed. */
  priority: number
  /** How far back the server keeps articles, in days. 0 means unlimited or unknown: always try it. */
  retentionDays: number
  /** How long to wait on the server before giving up on a connection or an answer. */
  timeoutSeconds: number
  /** When true a download is not failed for articles this server does not have. */
  optional: boolean
  /** When false the server is kept but never connected to. */
  enabled: boolean
  notes: string
  createdAt: string
  updatedAt: string
}

/**
 * How much a server's TLS certificate has to prove before the connection is used. Only applies
 * with SSL. Strict and medium check the chain and the host name; minimal checks the chain only;
 * disabled checks nothing.
 */
export type CertificateVerification = 'strict' | 'medium' | 'minimal' | 'disabled'

// --- The SDK

// --- Storage

/** The plugin's key/value store in the app's database: JSON values under keys of the plugin's choosing. */
export interface PluginStore {
  get<T = unknown>(key: string): T | undefined
  set(key: string, value: unknown): void
  delete(key: string): void
  /** Every key that starts with `prefix` (or every key), with its value. */
  list<T = unknown>(prefix?: string): { key: string, value: T }[]
}

/** One step of a plugin's own SQLite schema, run once and remembered by id, as the app's own are. */
export interface PluginMigration {
  /** Unique and sortable, such as `0001_history`. */
  id: string
  statements: string[]
}

// --- What the core lets a plugin see

/** A Usenet server as a plugin may see it: everything but the login. */
export type PluginServer = Omit<Server, 'username' | 'password'>

/** An RSS feed as a plugin may see it: everything but the URL, which carries the feed's key. */
export type PluginFeed = Omit<RssFeed, 'url'>

export interface PluginCore {
  downloads: {
    get(id: number): Download
    list(): Download[]
  }
  categories: { list(): Category[] }
  feeds: { list(): PluginFeed[] }
  servers: { list(): PluginServer[] }
}

// --- The context every hook gets

export interface PluginContext<S extends PluginSchema = PluginSchema, C extends PluginSchema = PluginSchema> {
  plugin: {
    id: string
    name: string
    /** The plugin's folder, for anything it keeps beside its code. */
    dir: string
  }
  /** The settings as saved on the plugin's page, every field validated against the schema. */
  settings: PluginSettingsOf<S>
  /**
   * What one category holds for the fields declared under `categorySettings`, as filled in on the
   * plugin's page. Every field at its default for a category that has not been filled in, for a
   * category that is not there any more, and for `null` — a download without a category.
   *
   * A download hook is handed its own download's values as `ctx.categorySettings` and rarely needs
   * this; a schedule or a route that works over several categories does.
   */
  categorySettingsFor(categoryId: number | null): PluginSettingsOf<C>
  store: PluginStore
  /**
   * The plugin's own SQLite file, opened on first use with the plugin's `migrations` applied.
   * Throws for a plugin that declares none.
   */
  readonly db: Database
  core: PluginCore
  /** A line in the server log under the plugin's tag. */
  log(message: string): void
  /** An entry in the audit log, shown on the plugin's page. `detail` is kept as it is given. */
  audit(event: string, detail?: Record<string, unknown>): void
  /** A message through the notifications the user has set up and asked to hear from plugins. */
  notify(message: { title: string, message: string }): Promise<void>
  /**
   * The address one of the plugin's own routes answers at, from outside: what goes into
   * Telegram's `setWebhook`, Sonarr's webhook box or a Shortcut. The token is already on it for a
   * route that takes one, so what comes back is a working address and a secret — log it nowhere.
   *
   * `path` is the route's own path, as declared. Throws when the plugin declares no such route,
   * and when nobody has filled in the app's external address under Settings → Integrations, since
   * there is nothing to build an address out of then. A plugin that registers a webhook should
   * let that reason through: it reads on its page as the reason its setup could not finish.
   */
  routeUrl(path: string): string
}

// --- Hooks

/** What every hook about one download gets: the download, and what its category holds. */
export interface DownloadContext<
  S extends PluginSchema = PluginSchema,
  C extends PluginSchema = PluginSchema,
> extends PluginContext<S, C> {
  /** The download as it stands. A copy: changing it changes nothing. */
  download: Download
  /**
   * The per-category settings for this download's category — the same thing
   * `categorySettingsFor(download.categoryId)` gives, read for you. Every field at its default
   * when the plugin declares no `categorySettings`, and for a download without a category.
   */
  categorySettings: PluginSettingsOf<C>
}

/** The same, for the hooks that fire while the download is on its way somewhere. */
export interface DownloadHookContext<
  S extends PluginSchema = PluginSchema,
  C extends PluginSchema = PluginSchema,
> extends DownloadContext<S, C> {
  /** The folder the download is (or was) headed for. */
  destination: string
}

export interface CommandResult {
  code: number
  stdout: string
  stderr: string
}

/** One of the files about to be moved into place, with the three things a plugin may do to it. */
export interface PluginFile {
  /** The file's name, without its folders. */
  name: string
  /** Its folders inside the download, `sub/dir/name.mkv`, or just the name at the top level. */
  relativePath: string
  /** Where it is on disk right now. */
  path: string
  sizeBytes: number
  /** Lower case, without the dot: `mkv`, or an empty string. */
  extension: string
  isVideo: boolean
  isArchive: boolean
  /** Deletes the file. */
  remove(): Promise<void>
  /** Gives the file another name in the folder it is in. A path is not a name. */
  rename(newName: string): Promise<void>
  /**
   * Puts the file where the plugin wants it in the destination, rather than leaving it to the move
   * — `placeAt('S01/one.mkv')` — and answers with where it actually landed.
   *
   * A placed file is out of the move: the next plugin does not see it, and the app does not move it
   * again. A whole folder is placed by placing each of its files under the same prefix, which keeps
   * it as it was; what that empties is cleared away. Nothing already there is overwritten — a taken
   * name gets a number, which is why the answer is worth reading. A path that would leave the
   * destination throws, as does a segment that is not a name.
   *
   * Only while the download is being moved, which is `download:beforeMove`; it throws anywhere
   * else. Decide first and place last: a download failed after a file was placed keeps the file
   * where the plugin put it.
   */
  placeAt(relativePath: string): Promise<string>
}

/**
 * What a hook that is handed the download's files on disk gets. The files are listed afresh for
 * each plugin in turn, so one plugin sees what the one before it left.
 */
export interface DownloadFilesContext<
  S extends PluginSchema = PluginSchema,
  C extends PluginSchema = PluginSchema,
> extends DownloadHookContext<S, C> {
  /** What came out of the archives, plus whatever was never an archive or a par2 to begin with. */
  files: PluginFile[]
  /** The folder the files sit in, for a plugin that walks it itself. */
  dir: string
  /** Runs a program, in `dir` unless told otherwise. Killed with the download when it is cancelled. */
  run(command: string[], options?: { cwd?: string }): Promise<CommandResult>
  /** Pulled when the download is cancelled or removed while the plugin is at work. */
  signal: AbortSignal
}

/** What `download:beforeMove` gets: the files as they are about to be moved into the destination. */
export type BeforeMoveContext<
  S extends PluginSchema = PluginSchema,
  C extends PluginSchema = PluginSchema,
> = DownloadFilesContext<S, C>

/** How a `download:beforeMove` hook fails the download on purpose. Throwing is a bug in the plugin, and is ignored. */
export interface BeforeMoveFailure {
  fail: string
}

/**
 * What `postprocess:failed` gets: everything `download:beforeMove` does, plus which step failed
 * and why. The files are still in the temp folder, so a triage plugin can look at what came down.
 */
export interface PostProcessFailedContext<
  S extends PluginSchema = PluginSchema,
  C extends PluginSchema = PluginSchema,
> extends DownloadFilesContext<S, C> {
  /** The step that failed: `verifying` is par2, `extracting` is unrar, `moving` is the move itself. */
  stage: PostProcessStage
  /** Why it failed, in the words the download's row is about to take. */
  error: string
}

/**
 * How a `postprocess:failed` hook sends the download round again instead of letting it fail: back
 * at the end of the queue, fetched from the start, as pressing "Retry" would. Nothing returned
 * lets the failure stand, which is the usual answer.
 *
 * The plugin decides when to give up — count the attempts in `ctx.store` or its own `ctx.db` — but
 * the app will not send one download round again more than a few times, however often it is asked.
 */
export interface PostProcessRetry {
  retry: string
}

/** Where an NZB the app is about to queue came from. */
export type NzbSource = 'upload' | 'api' | 'feed' | 'watch'

/** One of the files an NZB lists, as a plugin sees it. */
export interface NzbFileInfo {
  /** The subject line as posted. */
  subject: string
  /** The file name the subject names (`abc.r01` in `"abc.r01" yEnc (1/20)`), or null when it names none. */
  name: string | null
  poster: string
  /** ISO 8601: when it was posted, or null when the NZB does not say. */
  postedAt: string | null
  groups: string[]
  /** The articles added up, yEnc overhead included. */
  sizeBytes: number
  /** How many articles the file is posted in. */
  articles: number
}

/**
 * An NZB as it has been read, on its way into the download queue: what it holds, and what it is
 * about to become. Whatever brought it in — an upload, the SABnzbd API, a feed, the watch folder
 * — this is the same shape, so one hook covers every way a download can start.
 */
export interface OfferedNzb {
  source: NzbSource
  /** The job name it would be queued under, which is also the folder its result would land in. */
  name: string
  /** The category it would go to, or null for the default downloads folder. */
  categoryId: number | null
  /** Whether par2 and unrar would be run over what comes down. */
  postProcess: boolean
  /** `<meta type="title">`, or null. */
  title: string | null
  /** Whether the NZB carries an archive password. The password itself is not passed on. */
  hasPassword: boolean
  /**
   * What identifies the release the NZB points at: its article ids, hashed. The same post from two
   * indexers, under two names, has one fingerprint — what a dedupe plugin keys on.
   */
  fingerprint: string
  /** What the NZB says the articles add up to. */
  totalBytes: number
  totalArticles: number
  files: NzbFileInfo[]
}

export interface NzbParsedContext<
  S extends PluginSchema = PluginSchema,
  C extends PluginSchema = PluginSchema,
> extends PluginContext<S, C> {
  nzb: OfferedNzb
}

/**
 * How an `nzb:parsed` hook turns an NZB away: it is never queued, and whoever handed it over is
 * told the reason. Nothing returned lets it through, which is the usual answer.
 */
export interface NzbRejection {
  reject: string
}

/** A release as a feed or the watch folder offers it, before the filters see it. */
export interface OfferedRelease {
  title: string
  sizeBytes: number | null
  publishedAt: string | null
  source: 'feed' | 'watch'
  /** The feed it came from, for a feed's release. */
  feed: { id: number, name: string, categoryId: number | null } | null
  /** The feed's own word for what kind of release it is, when it gave one. */
  category: string | null
  /** The file's name in the watch folder, for a dropped NZB. */
  fileName: string | null
}

export interface ReleaseOfferedContext<
  S extends PluginSchema = PluginSchema,
  C extends PluginSchema = PluginSchema,
> extends PluginContext<S, C> {
  release: OfferedRelease
}

/**
 * What a `release:offered` hook may decide: drop it (with a reason for the log), queue it (to a
 * category, post-processed unless said otherwise), or give it another title for the filters to
 * see. Nothing decided is the usual answer: the release goes on to the filters as it is.
 */
export type ReleaseDecision =
  | { drop: string }
  | { accept: { categoryId?: number | null, postProcess?: boolean } }
  | { rename: string }

type Awaitable<T> = T | Promise<T>

export interface PluginHooks<S extends PluginSchema = PluginSchema, C extends PluginSchema = PluginSchema> {
  'download:added'?: (ctx: DownloadContext<S, C>) => Awaitable<void>
  'download:started'?: (ctx: DownloadHookContext<S, C>) => Awaitable<void>
  'download:paused'?: (ctx: DownloadHookContext<S, C>) => Awaitable<void>
  'download:resumed'?: (ctx: DownloadHookContext<S, C>) => Awaitable<void>
  'download:beforeMove'?: (ctx: BeforeMoveContext<S, C>) => Awaitable<BeforeMoveFailure | void>
  'postprocess:failed'?: (ctx: PostProcessFailedContext<S, C>) => Awaitable<PostProcessRetry | void>
  /** A download that ended in `completed`. One that failed is `download:failed`. */
  'download:finished'?: (ctx: DownloadHookContext<S, C>) => Awaitable<void>
  'download:failed'?: (ctx: DownloadHookContext<S, C>) => Awaitable<void>
  'download:removed'?: (ctx: DownloadContext<S, C>) => Awaitable<void>
  'nzb:parsed'?: (ctx: NzbParsedContext<S, C>) => Awaitable<NzbRejection | void>
  'release:offered'?: (ctx: ReleaseOfferedContext<S, C>) => Awaitable<ReleaseDecision | void>
}

// --- Choices a plugin looks up

/**
 * Where a `select` field's choices come from when the manifest cannot name them: the libraries a
 * Plex server holds, the chats a bot is in. The plugin declares these under `options` and points
 * a field at one by name with `optionsFrom`; the form asks for them as it is drawn, and shows
 * whatever went wrong instead of the field when the lookup fails.
 *
 * What is saved is the value that was picked, and it is not checked against this list on the way
 * in — by the time the plugin reads it the list may have moved on, so treat a value that is no
 * longer offered as one to cope with rather than one that cannot happen.
 */
export type PluginOptionProvider<S extends PluginSchema = PluginSchema, C extends PluginSchema = PluginSchema> =
  (ctx: PluginContext<S, C>) => Awaitable<{ value: string, label: string }[]>

// --- Notification targets, routes, schedules

/** A target the plugin adds to the notifications page, next to Discord and the custom webhook. */
export interface PluginNotificationKind<
  S extends PluginSchema = PluginSchema,
  F extends PluginSchema = PluginSchema,
  C extends PluginSchema = PluginSchema,
> {
  /** A word of the plugin's choosing; the app stores it as `<plugin id>:<kind>`. */
  kind: string
  label: string
  /** Where the details come from, under the fields. */
  hint?: string
  /** What one target of this kind takes: a token, a chat id. Drawn in the dialog in place of the URL box. */
  fields: F
  /** Sends one message to one target. Throwing marks the target's row as failed, as a webhook that does not answer does. */
  send(ctx: PluginContext<S, C>, message: NotificationMessage, config: PluginSettingsOf<F>): Awaitable<void>
  /** "Send test": reach the target with the details as typed, saving nothing. `send` with a test message when left out. */
  test?(ctx: PluginContext<S, C>, config: PluginSettingsOf<F>): Awaitable<void>
}

export interface PluginRequest {
  method: PluginRouteMethod
  /** The path under the plugin's prefix, as the route declared it. */
  path: string
  /** The query, less `token`: that one is the app's, and is taken off before the handler sees it. */
  query: Record<string, string>
  /** Every header but the session cookie and `Authorization`, which are the app's. */
  headers: Record<string, string>
  /** The body parsed as JSON, or the raw text when it is not JSON, or null when there is none. */
  body: unknown
  /** How this call was let in, which is the route's own `access`. */
  access: PluginRouteAccess
  /** Who called, as the server sees it (`X-Forwarded-For` first), or null when it cannot tell. */
  ip: string | null
}

/**
 * A handler under `/api/plugins/<plugin id>/<path>`. It may return anything JSON can carry, or a
 * `Response` for full say over status and headers.
 *
 * `access` decides who gets to call it. The default, `session`, is the app's own sign-in, which
 * is all a page of the app's own needs. The other two open the route to the outside, which is
 * what a webhook is: `token` lets in whoever sends the plugin's token, and `public` lets in
 * anyone at all. See `PluginRouteAccess` for which to reach for.
 */
export interface PluginRoute<S extends PluginSchema = PluginSchema, C extends PluginSchema = PluginSchema> {
  method: PluginRouteMethod
  /** One or more segments, such as `metrics` or `items/recent`. */
  path: string
  /** Who may call it. `session` — the app's sign-in — when left out. */
  access?: PluginRouteAccess
  handler(ctx: PluginContext<S, C>, request: PluginRequest): Awaitable<unknown>
}

/**
 * Something the plugin runs on its own, on a clock. Either `everyMinutes` — counted from the end
 * of the last run, so a slow run never overlaps itself — or `cron`, a five-field expression read
 * in the server's time zone, for work that belongs at a time of day rather than at an interval.
 * One of the two, never both.
 *
 * A plugin may declare several; give each a `name` then, since that is what the page shows and
 * what the last-run time is kept under.
 */
export interface PluginSchedule<S extends PluginSchema = PluginSchema, C extends PluginSchema = PluginSchema> {
  /** Required once a plugin has more than one schedule: letters, digits and underscores. */
  name?: string
  /** How often `run` is called, counted from the last run; one at the least. */
  everyMinutes?: number
  /** `minute hour day-of-month month day-of-week`, such as `0 4 * * *` for every day at 04:00. */
  cron?: string
  run(ctx: PluginContext<S, C> & { lastRunAt: string | null }): Awaitable<void>
}

// --- The plugin

export interface PluginDefinition<S extends PluginSchema = PluginSchema, C extends PluginSchema = PluginSchema> {
  /** Must be the folder's name: lower case, digits, dashes and underscores. */
  id: string
  name: string
  description?: string
  /** The plugin's own version, shown on the page. */
  version: string
  /**
   * The SDK major this plugin was written against, as a literal. Write the number down rather
   * than reading it from anywhere: it is what the plugin claims, not what it is running on.
   *
   * It never decides whether the plugin loads. A plugin built for another version loads, switches
   * on and runs like any other; the difference is a line on its row, so whoever installed it knows
   * what they have. What is removed in one major keeps working through the next before it goes,
   * so one major behind is inside the window and further back is not.
   */
  sdkVersion: number
  /** The SDK minor beside it, also a literal. Left out means 0. */
  sdkMinor?: number
  /** The settings that hold for the whole plugin, filled in once on its page. */
  settings?: S
  /**
   * A second schema, filled in once per category: the fields that differ between the categories
   * the plugin runs for — a quality per category, a library per category. The plugin's page draws
   * one form per category it runs for, and every download hook is handed its download's values as
   * `ctx.categorySettings`.
   *
   * Keep here only what genuinely differs; anything the same everywhere belongs in `settings`,
   * where it is filled in once.
   */
  categorySettings?: C
  /** Where a `select` field's choices come from when it names one with `optionsFrom`. */
  options?: Record<string, PluginOptionProvider<S, C>>
  /** The plugin's own SQLite schema, in `ctx.db`. Leave out for a plugin that only needs `ctx.store`. */
  migrations?: PluginMigration[]
  hooks?: PluginHooks<S, C>
  notifications?: PluginNotificationKind<S, PluginSchema, C>[]
  routes?: PluginRoute<S, C>[]
  /** One schedule, or several, each with a `name`. */
  schedule?: PluginSchedule<S, C> | PluginSchedule<S, C>[]
  /** Run when the plugin is switched on, and again at every startup while it is. */
  setup?(ctx: PluginContext<S, C>): Awaitable<void>
  /** Behind the "Test" button on the plugin's page. Return a word for the page, or throw. */
  test?(ctx: PluginContext<S, C>): Awaitable<string | void>
}

/** Types the definition and hands it back. The runtime module the app provides does the same. */
export function definePlugin<S extends PluginSchema = PluginSchema, C extends PluginSchema = PluginSchema>(
  plugin: PluginDefinition<S, C>,
): PluginDefinition<S, C> {
  return plugin
}

/** What `definePlugin` accepts, without the schemas pinned down: how the app types what it imported. */
export type AnyPluginDefinition = PluginDefinition<PluginSchema, PluginSchema>
